import Image from "next/image"
import { RarityTypeImg } from "../components/microComponents/images"
import types from "../local-json/types"
import variations from "../local-json/variations"

const Rarity = () => {
  return (
    <div className="rarity" id="rarity">
      <div className="container">
        <div className="rarity-card">
          <h3 className="section-title">Rarity</h3>
          <p>
            Each NFT is algorithmically generated by combining 170+ uniqu traits
            with varying rarity across categories.
          </p>

          <div className="rarity-card-grid">
            <div className="rarity-types">
              <h4 className="rarity-title">Types</h4>

              {types.map((type) => (
                <div className="rarity-row" key={type.id}>
                  <div className="rarity-number">{type.title}</div>
                  <div className="rarity-row-text">{type.text}</div>
                </div>
              ))}

              <div className="type-img">
                <Image src={RarityTypeImg} />
              </div>
            </div>

            <div className="rarity-variations">
              <h4 className="rarity-title">Variations</h4>

              {variations.map((variant) => (
                <div className="rarity-row" key={variant.id}>
                  <div className="rarity-number">{variant.number}</div>
                  <div className="rarity-row-text">{variant.text}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Rarity
