import Head from "next/head"

// Components
import Hero from "../components/Hero"
import GetRobots from "../components/GetRobots"
import Rarity from "../components/Rarity"
import Faq from "../components/Faq"
import Intermission from "../components/Intermission"

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <GetRobots />
      <Intermission />
      <Rarity />
      <Faq />
    </div>
  )
}
