import Head from "next/head"
import YourStuffHero from "../components/YourStuffHero"

export default function YourStuff() {
  return (
    <div className="page your-stuff">
      <Head>
        <title>Your Stuff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <YourStuffHero />
    </div>
  )
}
